/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class test */

#ifndef _Included_test
#define _Included_test
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     test
 * Method:    Display
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_test_Display
  (JNIEnv *, jobject);

/*
 * Class:     test
 * Method:    Add
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_test_Add
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     test
 * Method:    DisplayString
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_test_DisplayString
  (JNIEnv *, jobject, jstring);

/*
 * Class:     test
 * Method:    CallMe
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_test_CallMe
  (JNIEnv *, jobject);

/*
 * Class:     test
 * Method:    CallMeString
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_test_CallMeString
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
